name: Publish image

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  publish_image:
    name: Publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set variables
      id: vars
      run: |
        GITHUB_REPOSITORY_LC=$(echo "${GITHUB_REPOSITORY}" | tr [A-Z] [a-z])
        echo "::set-output name=name::${GITHUB_REPOSITORY_LC}"

        VERSION=$(git describe --tags)
        echo "::set-output name=version::${VERSION}"

        DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo "::set-output name=date::${DATE}"

        if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
          TAG="development"
          TAGS="dev"
        else
          VERSION_MAJOR=$(echo ${VERSION} | sed -r 's/([0-9]+).*/\1/')
          VERSION_MINOR=$(echo ${VERSION} | sed -r 's/([0-9]+).([0-9]+).*/\1.\2/')

          TAG="${VERSION}"
          TAGS="${VERSION_MAJOR} ${VERSION_MINOR} latest"
        fi
        echo "::set-output name=tag::${TAG}"
        echo "::set-output name=tags::${TAGS}"

    - name: Build
      run: |
        docker build -t \
          ${{ steps.vars.outputs.name }}:${{ steps.vars.outputs.tag }} \
          --build-arg BUILD_DATE=${{ steps.vars.outputs.date }} \
          --build-arg BUILD_VERSION=${{ steps.vars.outputs.version }} \
          .

        # If this tag has multiple tags, publish them too
        for tag in ${{ steps.vars.outputs.tags }}; do
          docker tag ${{ steps.vars.outputs.name }}:${{ steps.vars.outputs.tag }} \
            ${{ steps.vars.outputs.name }}:${tag}
        done

    - name: Publish
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "Skipping, as no DOCKER_USERNAME is set"
        else
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ steps.vars.outputs.name }}
        fi
